
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjUwNjJjODc4YThhNWFiZGExNDE1YiIsImVtYWlsIjoiZ2lnaUBjLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjYwMjUwOSwiZXhwIjoxNzMyNjg4OTA5fQ.IE4ENO8MN5KN7TFgPFvTjuXB_z9sg1N88KVWbYwTUEo
@baseUrl = http://localhost:3000
@users = users
@auth = auth
@feature = feature
GET  {{baseUrl}}/{{users}}
content-type: application/json
x-access-token: {{token}}

###

POST {{baseUrl}}/{{auth}}/login
content-type: application/json

{
   "email":"gigi@c.com",
   "password":"gigi123"
}

###

//for Auth Feature
PUT {{baseUrl}}/{{feature}}/6731ca496a893cec2aeecdb5 
content-type: application/json
x-access-token: {{token}}

{
  "permissions": [
    {
      "role": "Admin",
      "permissions": [
        "Create",
        "Read",
        "Update"
      ]
    },
    {
      "role": "User",
      "permissions": [
        "Read"
      ]
    },
     {
      "role": "Public",
      "permissions": [
        "Read"
  
      ]
    }
]
}
###
POST {{baseUrl}}/{{auth}}/signup
content-type: application/json

{
   "email":"sanimshrestha.60@gmail.com",
   "password":"test",
   "name":"Sanim",
   "phone":"9808405273",
   "gender":"Male"
}
